POST http://localhost:8010/api/site_preferences_analysis
Accept: */*
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache

{
  "interval": 10000000,
  "interval_slices_limit": 20,
  "counting": "visits",
  "category": "country",
  "category_items_limit": "10"
}
###
